### PR TITLE
Add description and references

### PR DESCRIPTION
**Pull request by Bobfrat**
@lukecampbell please review. This addresses https://github.com/ioos/compliance-checker/issues/291

screen shot 2016-09-07 at 2 09 24 pm

### CODE REVIEW

**Comment by lukecampbell** [comment]
This is a good start but we should go through the individual tests and plugins and make sure that the descriptions are appropriate. I know that the original issue @rsignell-usgs raised isn't addressed by this because the description for the NCEI checks is still completely vague.

screen shot 2016-09-07 at 2 34 49 pm

**Comment by Bobfrat** [comment]
@lukecampbell agreed, the reference link to NCEI NetCDF templates help but the ```_cc_description``` attributes should be updated. In fact the Glider DAC plugin doesn't have a description at all.

**Comment by mbiddle-nodc** [comment]
NCEI can help come up with better language for the NCEI checks.

**Comment by Bobfrat** [comment]
@mbiddle-nodc that would be awesome.

A search for _cc_description in the https://github.com/ioos/cc-plugin-ncei repo shows where all the descriptions are currently defined. You can pass along the descriptions to me and I'll make the updates or just make a PR to that repo directly.

https://github.com/ioos/cc-plugin-ncei/search?utf8=%E2%9C%93&q=_cc_description

**Comment by mbiddle-nodc** [comment]
This might take a little bit to get the language together. @Bobfrat I'll notify you once we have all the descriptions ready.

**Comment by mbiddle-nodc** [comment]
I'm not very fluent in github, but I think I made the changes and put the pull requests in. Let me know if it didn't work.

**Comment by Bobfrat** [comment]
👍 Looks good I'll have @lukecampbell review and merge. Thanks!

**Pull request merged**
