### PR TITLE
Adds python3 support

### LINKED ISSUE #32: Python 3
Can we get a python 3 compatible version?

### PR DESCRIPTION
**Pull request by lukecampbell**
Fixes #32

### CODE REVIEW

**Comment by lukecampbell** [comment]
@kwilcox @daf Want to give this a try?

**Comment by kwilcox** [comment]
@RSully

**Comment by RSully** [comment]
Going forward how important is backwards-compatibility to 2.7?

**Comment by lukecampbell** [comment]
I haven't heard from anyone that we're no longer supporting 2.7 so, I think it's still a priority to support both versions.

**Comment by RSully** [comment]
This seems to run on Python 3.5 here :+1:

**Comment by daf** [comment]
thanks @lukecampbell !

**Comment by lukecampbell** [comment]
@RSully if you pip install cc-plugin-ncei it will show up in the compliance-checker web.

**Pull request merged**
