### PR TITLE
use netcdf4>=1.6.0 to avoid bad wheel

### LINKED ISSUE #116: Redeploy to catch the latest 4.3.4 version of complicance-checker
@benjwadams it looks like the cc version in the web deployed is 4.3.3 instead of 4.3.4. How difficult it is to deploy the latest one?
Is that something we should automate?

cc @MathewBiddle

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #116 and https://github.com/ioos/ioos_code_lab/issues/29

@benjwadams do you mind re-deploying after we merge this one?

### CODE REVIEW

**Comment by ocefpaf** [comment]
@benjwadams not sure if you are the right person to ping here but we could really use an updated deployment of the cc-web.

**Comment by MathewBiddle** [comment]
@mwengren can you help here?

**Comment by ocefpaf** [comment]
Folks, this is blocking users to check their data using compliance-checker web. It is not a bug change, just one package update. @benjwadams can you help us out here?

**Comment by MathewBiddle** [comment]
Any updates on this? Can we merge it?

**Comment by ocefpaf** [comment]
We need RPS to re-deploy this to be able to see this change in the web app.

**Comment by mwengren** [comment]
@benjwadams Can you handle redeploying the CC web app step?  Thanks!

**Pull request merged**
