### PR TITLE
Update about page

### PR DESCRIPTION
**Pull request by Bobfrat**
Some styling and content updates to the about page.

screen shot 2017-12-05 at 11 16 10 pm
screen shot 2017-12-05 at 11 16 19 pm

### CODE REVIEW

**Comment by gitchrisadams** [comment]
Looks good.

**Comment by jbosch-noaa** [comment]
This looks great!  Thanks @Bobfrat .

**Comment by daf** [comment]
@Bobfrat I think there should be more consistency with capitalization - the top two questions refer to "compliance checker" whereas others are "Compliance Checker".  I'd suggest the latter everywhere.

**Comment by jbosch-noaa** [comment]
Good catch, Dave.

**Comment by jbosch-noaa** [comment]
@BeckyBaltes, @mwengren   - I have asked RPS to make the Compliance Checker API a little more friendly.  Do you have any other suggestions to the addition of a "Frequently Asked Questions" page they are going to add?

**Comment by BeckyBaltes** [comment]
@jbosch-noaa My other question would be, "How do I use the compliance checker?" or "Who can use the checker?" (in other words, is it open to anyone?) If it is intuitive when the checker is open how to use it, that question may not be necessary.

**Comment by jbosch-noaa** [comment]
Thanks @BeckyBaltes .  The Compliance Checker should be open for anyone to use.  The website however, seems pretty intuitive. Bob does note in his "What is the Compliance Checker?" section that you can upload or submit a link on the website to run a check on a file.

**Comment by BeckyBaltes** [comment]
Right, I know the answers. Just thought it might worth including that it's open to all as an FAQ.  The "what is a Compliance Checker?" answer is probably good enough to cover the how to.

**Pull request merged**
